### ISSUE TITLE
ImportError: No module named bitmex

### ISSUE THREAD

**Issue by P31254** [coinpit/pymmbot#1]
Hi, I decided to give the bot a go and installed it on Ubuntu. Unfortunately I'm getting error: "No module named bitmex"

$ sudo python mmbot.py
Traceback (most recent call last):
  File "mmbot.py", line 3, in <module>
    from pymmbot import mmbot
  File "/home/ubuntu/c/pymmbot/mmbot.py", line 7, in <module>
    from pymmbot.bitmex import bitmex
ImportError: No module named bitmex

Any ideas how to resolve this?

**Comment by nirmalgupta** [comment]
Are you using python 3?

**Comment by P31254** [comment]
Thanks, although I installed python 3.5.2 I was using Python 2.7

Now, with Python3 I still get a similar error:

```
> python3 mmbot.py
> #### bitmex https://testnet.bitmex.com/api/v1/
> #### coinpit https://live.coinpit.me/api/v1
> Traceback (most recent call last):
>   File "mmbot.py", line 3, in <module>
>     from pymmbot import mmbot
>   File "/home/ubuntu/c/pymmbot/mmbot.py", line 7, in <module>
>     from pymmbot.bitmex import bitmex
>   File "/home/ubuntu/c/pymmbot/bitmex/bitmex.py", line 7, in <module>
>     from pymmbot.bitmex.auth import APIKeyAuthWithExpires
>   File "/home/ubuntu/c/pymmbot/bitmex/auth/APIKeyAuthWithExpires.py", line 5, in <module>
>     from future.builtins import bytes
> ImportError: No module named 'future'
```
>

I'm not particularly experienced with python so any help is much appreciated.

**Comment by nirmalgupta** [comment]
You should use virtual environment for python3. You can find documentation to do that [here](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-ubuntu-16-04#step-2-—-setting-up-a-virtual-environment).

then you will have to run ./build.sh under cpmmbot.py folder. Please let us know if it solves your problem. or you can directly come at [telegram](https://t.me/joinchat/AAAAAEDRZj-ULeiURpBSQw) as well.

**Comment by nirmalgupta** [comment]
did you update your view in last 2 days? looks like you may not have latest version.

**Comment by P31254** [comment]
Thanks a lot. Using  virtual environment resolved the errors. 
I don't know what did you mean by "view" but I updated all the packages and downloaded the most up to date copy of the bot.
